### ISSUE TITLE
Select link has issues running a single link, might not be correctly working in general

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#59] opened 2016-09-20 15:01 UTC
@bstabler and @gregmacfarlane  Here's the email I just wrote:

"I ran the select link for the Columbia River crossing – it seemed to run without error, which might be a bad thing (at least in this case).
The trips that came out of the select link run only worked for one direction on the bridge (the outbound direction (into Washington), and the number of trips that were identified in the process is about half of what the volume on the link says there should be.  So there is clearly some issue occurring that needs to be investigated."

Specifically I ran the following select link in t20 of the reference, the data is on SWIM 1:
G:\swim2\Reference\inputs\t0

IN - 152456-160705
OUT - 159550-152457

**Comment by bettinardi** [comment] 2016-11-01 19:29
@nsdhakar and @bstabler - 
If possible, as we revise the select link tool to work for a single link, it would be very helpful to get ODOT as many pieces as possible to a related product.  We have found that when doing a select link, an important question is, "who is using the link now", and where would those users go if that link was not available.  So an easy output to add to the single select link process, would be to create two sets of demand matrices - the demand that uses the select link and the demand that doesn't (for both autos and trucks).  The next piece (that is farther outside of existing scope) would be to setup SWIM procedure files to run assignment with 4 demand segments; auto and truck, for both select link and non-select link demand.  A user could then run the SWIM select link analysis for a link.  Generate the matrices.  Then close the link in Visum and run assignment with the 4 demand segments and see where the demand for that link re-routed (the third potential product could be Visum gpa files to view the results).  We might not be able to do all of this under the existing scope / timelines.  But I wanted you to be aware that's what one of the things we are hoping to do with it, so you can get us as close as you can, or at least be thinking about it, when you design the tool.

**Comment by bstabler** [comment] 2016-11-09 19:40
@nsdhakar and I discussed how best to integrate the new one link version of ``SL - Append Select Link To Trips`` and plan to do the following:

Revise the runSL function in [model_runner/module_commands.py](https://github.com/pbsag/tlumip/blob/master/root/scenario/model/code/model_runner/module_commands.py) to read the selectLink.csv file
  - if one link, then run the two Python scripts:
    - build_select_link_matrices.py - existing script to generate select link data
    - append_selectlink_data.py - new script to append select link data to trips if only one select link
  - else if more than one link:
    - Run the existing ``SL - Generate Select Link Data`` and ``SL - Append Select Link To Trips`` modules through the Java runner which calls build_select_link_matrices.py and also runs the Java programs to process the results and append select link data to trips

**Comment by nsdhakar** [comment] 2016-11-10 17:18
@bettinardi: what is a single link - is it one direction link (IN or OUT) or both directions (IN+OUT)?

**Comment by bstabler** [comment] 2016-11-10 20:11
I think one directed link makes sense and, if you want two links, then add the results up manually.

**Comment by bettinardi** [comment] 2016-11-10 20:19
I agree with Ben's comment/suggestion - but if there is budget, my preference would be for a two-directional select link - that is how we will be using it 99% of the time - and running two select link processes in SWIM and putting them together manually will get old.

**Comment by bettinardi** [comment] 2017-02-02 19:50
@jfdman 
We have a series of issues occurring with the select link tool that need to be addressed.  These might all be inter-linked, I'm having a really hard time troubleshooting these issues.

1. using the "build_run.bat" command creates a report to the screen for select link for some reason - it shouldn't do that.  If select link information is to be reported to the screen it should only be when the select link module is run.
2. The select link process, SL - Generate Select Link Data,  is not properly building the "selectLinkResults.csv".  Somehow that file will not update to match the information provided in the "selectLinks.csv" input.  The results file is recreated (with the correct date stamp), but somehow it is always using the original copy/run of the "selectLinks.csv" input.  It won't update.
3.  Possibly related to bullet 2 (and possibly also bullet 1), the selectLink zip result does not have the correct volume represented for the select links that were pulled (note they are not the correct links from the input file, but the ones that are pulled are not correct either).  Also note, that currently I have only been testing the condition with more than 1 link.  My guess is that this might work in the one link condition, and that adding that condition may have broke the multi-link option.
4.  In previous deliverables / tasks, we had listed that a summary output of the select link needed to be created.  The idea being that while we had all the select link trip tables in memory, to quickly write out a csv with the trips tabulated to the select link stations.  This needs to be completed.  It should be completed while fixing this problem, as it will help us identify more quickly if the fixes implemented are working or not.

After these issues are addressed, we can refocus on the scope for issue #68 https://github.com/pbsag/tlumip/issues/68
Which is also described in my second comment above under this issue.

**Comment by bstabler** [comment] 2017-02-16 05:42
SL module is now fixed.  Before SL was only running for peak and offpeak, but SWIM was running four assignments - peak, offpeak, pm, and ni.  This meant that the pm and ni assignment results (i.e. paths) were not available to the SL process.  The SL process joins the paths to the microsimulated trip lists by trip origin, destination, and time period.  If a microsimulated trip occured in the pm period, a path could not be joined since no paths from the pm were available for joining.  This is now fixed and SL requires all four time period assignments to be run.

The following properties were revised or added:
```
ta.pm.paths.version.file = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.OUTPUTS@/t@CURRENT.INTERVAL@/PM_PATHS.ver
ta.ni.paths.version.file = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.OUTPUTS@/t@CURRENT.INTERVAL@/NT_PATHS.ver
sl.visum.demand.segment.mapping = {'a_peak':1,'a_offpeak':2,'a_ni':3,'a_pm':4,'d_peak':5,'d_offpeak':6,'d_ni':7,'d_pm':8}
sl.auto.classes = a_peak,a_offpeak,a_pm,a_ni
sl.truck.classes = d_peak,d_offpeak,d_pm,d_ni
sl.cttrips.trace.origin = 3009
sl.cttrips.trace.destination = 2857
```
The last two are for specifying an OD pair to trace how many ct trips are joined during the SL process.  The results are written to the main event log file as follows:

```
16-Feb-2017 00:28, INFO, ctTrips trace origin=3009 dest=2857 3009,317,2857,9,9,223285,SU,3009,_1,1.0,3009,
16-Feb-2017 00:28, INFO, ctTrips trace origin=3009 dest=2857 3009,320,2857,9,9,223324,SU,3009,_1,1.0,3009,
16-Feb-2017 00:28, INFO, ctTrips trace origin=3009 dest=2857 3009,841,2857,9,9,260239,TT,3009,_1,1.0,3009,
```

which means 3 ct trips use the tagged select links.  This was confirmed by checking the number of trips in the select link matrices saved in the VISUM SL.ver file.

**Comment by bstabler** [comment] 2017-02-16 05:47
@nsdhakar - please update the SL wiki

**Comment by bettinardi** [comment] 2017-02-17 18:23
I am still testing.  Testing on the swim small seemed successful, next step will be to test both multi and single select link on a full run for actual projects (like the ABM and or testing flows across CRC).  

Outstanding items to review / address:

1. Add a “SDT_VEHICLE_TRIP” column to the SL_Summary file, where SDT is filtered down to just “DA”, “SR2” and “SR3P” on the tripMode, and then DA gets a value of 1, SR2 gets 0.5 and SR3P gets 0.3 and those values are summed so that the summary file can be used to compare to the auto vehicle trips on the link as well as the truck

2. Ensure that the SL_Summary table generates for multiple select link as well as single.

3. Develop a SL xml procedure file to run a multi-class assignment on the "_SL.ver" that is created.  Have that procedure run as part of the process (so that the user is left with a helpful SL multiclass assignment after SL completes.

4. - review the SL assignment (hasn't been reviewed by ODOT yet.  @nsdhakar - if you have a procedure that you used to review the matrices / version file that SL produces, please let me know.

I think this covers all the outstanding issues to address with SL.

**Comment by bettinardi** [comment] 2017-03-07 19:38
Related to bullets 3 & 4 above:
It looks as if several steps need to occur (beyond just the xml in bullet 3 above) to run the SL assignment.  
 - demand segements need to be updated to include the 16 new classes (4 periods x two modes x sl and remainder)
 - The matrix listing descriptions need to be updated so that the name is the same as the dsegcode.  If this step is completed than the new demand segements will automatically point to the 16 new matrices.
 - then an xml procedure file needs to be run (I have already set that up).  I think we need to consider whether we want to setup some additional formula matrices and have all of the demand stuff and matrices placeholders setup in the input version file.  That might simplify.  The reason I suggest formual matrices, is because I don't know if we will care about SL analysis by period as much as looking at a daily assignment, and so I think we will want the default to do a 4 way demand segement assignment instead of a 16 way assignment, where we collapse on the period and just have a daily by mode and select link versus remainder.
 - We will also need a graphic parameter file that auto loads after assignment is complete, so that the user can just open the select link version file and see what the select link looks like without any additional work.

One potential issue to fix - When I did my testing it said that there were negatives in all of the remainder matrices - we will need to look into that.  Figure out if there is an issue - and if it is just rounding - we will need to zero those negatives out (but before we zero out, let's make sure there is not a calculation issue).

**Comment by bettinardi** [comment] 2017-03-08 15:51
A couple more issues to correct with select link (note that these last three comments all need to be addressed with the select link process - so don't just focus on this current last comment):

 - Currently (at least with the Metro example), the process litters the folder directory with a bunch of empty (just header) "sl_weaving..." files.  We need to figure out why those are being created; if it is a problem; fix the problem if it exists; and then make sure that meaningless files are output to the directory.
 - additionally, the "SL" matrices do not appear to add to the "_SL.ver" file in a multi-select link configuration (I thought they were supposed to if the setting was on.
 - Last (this might be captured in the bullets above too), the sl_summary.csv file needs to work with the multi-select link and not just the single select link (and as noted above, we need vehicle trips for the SDT output, in addition to person trips).

**Comment by bettinardi** [comment] 2017-03-09 18:34
In addition to the three sets of comments above, we still have an issue where the multi-select link process is not pulling the correct number of trips (the issue appears to be isolated to SDT, but all trips should be checked and verified).  The primary issue is to get the process working; the three sets of comments above our secondary.

The issue has specifically been seen in the Metro boundary select link file - others may follow.

**Comment by bettinardi** [comment] 2017-06-02 16:23
One more -
The select link process should add / build the demand segments needed in the version file to run the select link multi-class assignment.

**Comment by bettinardi** [comment] 2017-06-02 16:24
Also to create the formula daily matrices for select link and remainder (auto and truck)

**Comment by bettinardi** [comment] 2017-06-02 16:42
Initial testing returns a warning identifying negative values in the demand matrices.  We will need to track down if there are indeed negative values in the matrices and where they are coming from.

**Comment by bettinardi** [comment] 2018-03-23 00:05
Closed this issue and spawned issues 90 and 91 from this list - starting clean with those new issues, also remember that #85 is related.

**Closed** 2018-03-23 00:04 UTC
